[config]

[config.wallpaper]
set = true
command = "awww img {{image}} --transition-type outer"




# GTK Applicatoin Theming
[templates.gtk3]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-gtk3.css"
output_path = "~/hyprdots/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-gtk4.css"
output_path = "~/hyprdots/.config/gtk-4.0/gtk.css"


# Hyprland
[templates.hypr]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-hypr.lua"
output_path = "~/hyprdots/.config/hypr/common/colors.lua"


# Zed Editor
[templates.zed]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-zed.json"
output_path = "~/hyprdots/.config/zed/themes/matugen.json"


# Ghostty
[templates.ghostty]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-ghostty"
output_path = "~/hyprdots/.config/ghostty/themes/Matugen"


# Alacritty
[templates.alacritty]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-alacritty.toml"
output_path = "~/hyprdots/.config/alacritty/themes/matugen.toml"


# Starship
[templates.starship]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-starship.toml"
output_path = "~/hyprdots/.config/starship.toml"


# Btop
[templates.btop]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-btop.theme"
output_path = "~/hyprdots/.config/btop/themes/matugen.theme"


# Rofi
[templates.rofi]
input_path = "~/hyprdots/.config/matugen/configuration/matugen-rofi.rasi"
output_path = "~/hyprdots/.config/rofi/colors.rasi"
