timeout: 30
interface_branding: Limine Bootloader (Linux)

term_palette: 24273a;ed8796;a6da95;eed49f;8aadf4;f5bde6;8bd5ca;cad3f5
term_palette_bright: 5b6078;ed8796;a6da95;eed49f;8aadf4;f5bde6;8bd5ca;cad3f5
term_background: 24273a
term_foreground: cad3f5
term_background_bright: 5b6078
term_foreground_bright: cad3f5

/Arch Linux (linux)
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: root=PARTUUID=<PARTUUID:-{blkid /dev/nvme****}> rw rootfstype=btrfs
    module_path: boot():/initramfs-linux.img
    comment: Boot into Arch Linux


/Windows 11
    protocol: efi
    path: uuid(<PARTUUID:-{blkid /dev/nvme****}>):/EFI/Microsoft/Boot/bootmgfw.efi
    comment: Boot into Windows 11
