-- ░█▄█░█▀█░▀█▀░█░█░█▀▀░█▀▀░█▀█░░░░░░░░░█░█░█░█░█▀█░█▀▄░█░░░█▀█░█▀█░█▀▄░░░░
-- ░█░█░█▀█░░█░░█░█░█░█░█▀▀░█░█░░░▄▄▄░░░█▀█░░█░░█▀▀░█▀▄░█░░░█▀█░█░█░█░█░░░░
-- ░▀░▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░░░░░░░▀░▀░░▀░░▀░░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀░░░░░
--
-- Automatically generated by MATUGEN
-- Made by Sain-Biswas <https://github.com/Sain-Biswas>

local colors = {}

colors.image = "/home/sainbiswas/hyprdots/wallpapers/mountains.jpg"


colors.background =  "rgba(1A1206FF)"

colors.error =  "rgba(FFB4ABFF)"

colors.errorContainer =  "rgba(93000AFF)"

colors.inverseOnSurface =  "rgba(382F20FF)"

colors.inversePrimary =  "rgba(7D5800FF)"

colors.inverseSurface =  "rgba(F1E0CAFF)"

colors.onBackground =  "rgba(F1E0CAFF)"

colors.onError =  "rgba(690005FF)"

colors.onErrorContainer =  "rgba(FFDAD6FF)"

colors.onPrimary =  "rgba(422C00FF)"

colors.onPrimaryContainer =  "rgba(FFDEA9FF)"

colors.onPrimaryFixed =  "rgba(271900FF)"

colors.onPrimaryFixedVariant =  "rgba(5F4100FF)"

colors.onSecondary =  "rgba(3C2F04FF)"

colors.onSecondaryContainer =  "rgba(F8E0A6FF)"

colors.onSecondaryFixed =  "rgba(241A00FF)"

colors.onSecondaryFixedVariant =  "rgba(544519FF)"

colors.onSurface =  "rgba(F1E0CAFF)"

colors.onSurfaceVariant =  "rgba(D4C4AFFF)"

colors.onTertiary =  "rgba(383000FF)"

colors.onTertiaryContainer =  "rgba(F4E393FF)"

colors.onTertiaryFixed =  "rgba(211C00FF)"

colors.onTertiaryFixedVariant =  "rgba(514704FF)"

colors.outline =  "rgba(9C8F7BFF)"

colors.outlineVariant =  "rgba(504535FF)"

colors.primary =  "rgba(FFBA29FF)"

colors.primaryContainer =  "rgba(5F4100FF)"

colors.primaryFixed =  "rgba(FFDEA9FF)"

colors.primaryFixedDim =  "rgba(FFBA29FF)"

colors.scrim =  "rgba(000000FF)"

colors.secondary =  "rgba(DBC48CFF)"

colors.secondaryContainer =  "rgba(544519FF)"

colors.secondaryFixed =  "rgba(F8E0A6FF)"

colors.secondaryFixedDim =  "rgba(DBC48CFF)"

colors.shadow =  "rgba(000000FF)"

colors.sourceColor =  "rgba(D0B790FF)"

colors.surface =  "rgba(1A1206FF)"

colors.surfaceBright =  "rgba(413828FF)"

colors.surfaceContainer =  "rgba(271E11FF)"

colors.surfaceContainerHigh =  "rgba(31291AFF)"

colors.surfaceContainerHighest =  "rgba(3D3324FF)"

colors.surfaceContainerLow =  "rgba(221A0DFF)"

colors.surfaceContainerLowest =  "rgba(140D03FF)"

colors.surfaceDim =  "rgba(1A1206FF)"

colors.surfaceTint =  "rgba(FFBA29FF)"

colors.surfaceVariant =  "rgba(504535FF)"

colors.tertiary =  "rgba(D7C77AFF)"

colors.tertiaryContainer =  "rgba(514704FF)"

colors.tertiaryFixed =  "rgba(F4E393FF)"

colors.tertiaryFixedDim =  "rgba(D7C77AFF)"


return colors
