-- ░█▄█░█▀█░▀█▀░█░█░█▀▀░█▀▀░█▀█░░░░░░░░░█░█░█░█░█▀█░█▀▄░█░░░█▀█░█▀█░█▀▄░░░░
-- ░█░█░█▀█░░█░░█░█░█░█░█▀▀░█░█░░░▄▄▄░░░█▀█░░█░░█▀▀░█▀▄░█░░░█▀█░█░█░█░█░░░░
-- ░▀░▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░░░░░░░▀░▀░░▀░░▀░░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀░░░░░
--
-- Automatically generated by MATUGEN
-- Made by Sain-Biswas <https://github.com/Sain-Biswas>

local colors = {}

colors.image = "/home/sainbiswas/hyprdots/wallpapers/genshin-impact-skirk.jpg"


colors.background =  "rgba(14121AFF)"

colors.error =  "rgba(FFB4ABFF)"

colors.errorContainer =  "rgba(93000AFF)"

colors.inverseOnSurface =  "rgba(322F38FF)"

colors.inversePrimary =  "rgba(166C47FF)"

colors.inverseSurface =  "rgba(E6E0ECFF)"

colors.onBackground =  "rgba(E6E0ECFF)"

colors.onError =  "rgba(690005FF)"

colors.onErrorContainer =  "rgba(FFDAD6FF)"

colors.onPrimary =  "rgba(003822FF)"

colors.onPrimaryContainer =  "rgba(A3F4C5FF)"

colors.onPrimaryFixed =  "rgba(002112FF)"

colors.onPrimaryFixedVariant =  "rgba(005233FF)"

colors.onSecondary =  "rgba(402843FF)"

colors.onSecondaryContainer =  "rgba(FCD7FBFF)"

colors.onSecondaryFixed =  "rgba(2A132DFF)"

colors.onSecondaryFixedVariant =  "rgba(583E5AFF)"

colors.onSurface =  "rgba(E6E0ECFF)"

colors.onSurfaceVariant =  "rgba(CAC4D5FF)"

colors.onTertiary =  "rgba(372856FF)"

colors.onTertiaryContainer =  "rgba(EBDDFFFF)"

colors.onTertiaryFixed =  "rgba(221240FF)"

colors.onTertiaryFixedVariant =  "rgba(4E3E6EFF)"

colors.outline =  "rgba(948E9FFF)"

colors.outlineVariant =  "rgba(494553FF)"

colors.primary =  "rgba(88D7AAFF)"

colors.primaryContainer =  "rgba(005233FF)"

colors.primaryFixed =  "rgba(A3F4C5FF)"

colors.primaryFixedDim =  "rgba(88D7AAFF)"

colors.scrim =  "rgba(000000FF)"

colors.secondary =  "rgba(DFBBDEFF)"

colors.secondaryContainer =  "rgba(583E5AFF)"

colors.secondaryFixed =  "rgba(FCD7FBFF)"

colors.secondaryFixedDim =  "rgba(DFBBDEFF)"

colors.shadow =  "rgba(000000FF)"

colors.sourceColor =  "rgba(2D38CEFF)"

colors.surface =  "rgba(14121AFF)"

colors.surfaceBright =  "rgba(3B3841FF)"

colors.surfaceContainer =  "rgba(211E26FF)"

colors.surfaceContainerHigh =  "rgba(2B2931FF)"

colors.surfaceContainerHighest =  "rgba(36333CFF)"

colors.surfaceContainerLow =  "rgba(1D1A22FF)"

colors.surfaceContainerLowest =  "rgba(0F0D15FF)"

colors.surfaceDim =  "rgba(14121AFF)"

colors.surfaceTint =  "rgba(88D7AAFF)"

colors.surfaceVariant =  "rgba(494553FF)"

colors.tertiary =  "rgba(D1BDF6FF)"

colors.tertiaryContainer =  "rgba(4E3E6EFF)"

colors.tertiaryFixed =  "rgba(EBDDFFFF)"

colors.tertiaryFixedDim =  "rgba(D1BDF6FF)"


return colors
