[colors.primary]
background = '#1c110e'
foreground = '#f5ddd8'

[colors.cursor]
text = '#f5ddd8'
cursor = '#e0bfb8'

[colors.vi_mode_cursor]
text = '#1c110e'
cursor = '#a4c9ff'

[colors.search.matches]
foreground = '#58413c'
background = '#aed197'

[colors.search.focused_match]
foreground = '#58413c'
background = '#a4c9ff'

[colors.footer_bar]
foreground = '#58413c'
background = '#f5ddd8'

[colors.hints.start]
foreground = '#58413c'
background = '#edbd92'

[colors.hints.end]
foreground = '#58413c'
background = '#edbd92'

[colors.selection]
text = '#1c110e'
background = '#a4c9ff'


[colors.normal]
black = "#1c110e"
red = "#ffb4ab"
green = "#a4c9ff"
yellow = "#edbd92"
blue = "#aed197"
magenta = "#93000a"
cyan = "#d4e3ff"
white = "#e0bfb8"


[colors.bright]
black = "#443632"
red = "#ffb4ab"
green = "#a4c9ff"
yellow = "#edbd92"
blue = "#aed197"
magenta = "#93000a"
cyan = "#d4e3ff"
white = "#f5ddd8"
