[colors.primary]
background = '#161309'
foreground = '#eae2cf'

[colors.cursor]
text = '#eae2cf'
cursor = '#d0c6ab'

[colors.vi_mode_cursor]
text = '#161309'
cursor = '#e8b4f8'

[colors.search.matches]
foreground = '#4d4632'
background = '#d7c77a'

[colors.search.focused_match]
foreground = '#4d4632'
background = '#e8b4f8'

[colors.footer_bar]
foreground = '#4d4632'
background = '#eae2cf'

[colors.hints.start]
foreground = '#4d4632'
background = '#bfcc9b'

[colors.hints.end]
foreground = '#4d4632'
background = '#bfcc9b'

[colors.selection]
text = '#161309'
background = '#e8b4f8'


[colors.normal]
black = "#161309"
red = "#ffb4ab"
green = "#e8b4f8"
yellow = "#bfcc9b"
blue = "#d7c77a"
magenta = "#93000a"
cyan = "#f8d8ff"
white = "#d0c6ab"


[colors.bright]
black = "#3d392c"
red = "#ffb4ab"
green = "#e8b4f8"
yellow = "#bfcc9b"
blue = "#d7c77a"
magenta = "#93000a"
cyan = "#f8d8ff"
white = "#eae2cf"
